[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--prefix=/opt/buildhome/.npm-global"

# Redirect all requests to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for VR/WebXR compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=*, microphone=*, geolocation=*, accelerometer=*, gyroscope=*, magnetometer=*, xr-spatial-tracking=*"
    Cross-Origin-Embedder-Policy = "credentialless"

# Caching for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"