// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqmnbjtocohomgawjxga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbW5ianRvY29ob21nYXdqeGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzcyMDUsImV4cCI6MjA2NTkxMzIwNX0._p6lOVjQ1QmGgLNtMrF6S6nfLdLynZ_lpBgNga1rYRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);